### Create new user
POST http://localhost:3030/users
Content-Type: application/json

{
  "user": "user2",
  "email": "your_email2",
  "displayName": "User2",
  "password": "user2"
}

### Login
POST http://localhost:3030/authentication
Content-Type: application/json

{
  "email": "your_email2",
  "password": "user2",
  "strategy": "local"
}
